<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '9',
    'typeid' => '0',
    'title' => '产品3的案例',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品3 保健 眼药',
    'description' => '很好的产品，请保持关注',
    'posids' => '0',
    'url' => 'http://mulan.com/index.php?m=content&c=index&a=show&catid=9&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1369541724',
    'updatetime' => '1384693781',
    'hitsid' => 'c-1-3',
    'views' => '19',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '产品1的案例',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品1 保健 眼药',
    'description' => '自从有了它，忘了我的她自从有了它，忘了我的她自从有了它，忘了我的她自从有了它，忘了我的她自从有了它，忘了我的她自从有了它，忘了我的...',
    'posids' => '0',
    'url' => 'http://mulan.com/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1369541593',
    'updatetime' => '1369998539',
    'hitsid' => 'c-1-1',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '产品2的案例',
    'style' => '',
    'thumb' => '',
    'keywords' => '产品2 保健 眼药',
    'description' => '很好的产品，请保持关注很好的产品，请保持关注很好的产品，请保持关注很好的产品，请保持关注很好的产品，请保持关注很好的产品，请保持关...',
    'posids' => '0',
    'url' => 'http://mulan.com/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1369541680',
    'updatetime' => '1369998546',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>